version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatapp_postgres
    environment:
      POSTGRES_DB: chatapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatapp_network

  redis:
    image: redis:7-alpine
    container_name: chatapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatapp_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatapp_server
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatapp_db
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your_jwt_secret_here
      CLIENT_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    networks:
      - chatapp_network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chatapp_client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - chatapp_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  chatapp_network:
    driver: bridge